### ISSUE TITLE
Crimson crashes on vep stats with no data

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [bow/crimson#13]
When an entry in the vep stats output has no data, crimson crashes while parsing the stats file.

Example data:
```
[Coding consequences]

[SIFT summary]

[PolyPhen summary]
```
Running crimson
```bash
crimson vep no-variants.vep_stats.txt
Traceback (most recent call last):
  File "/anaconda3/envs/hamlet-devel/bin/crimson", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/crimson/cli.py", line 154, in vep
    payload = m_vep.parse(input)
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/crimson/vep.py", line 99, in parse
    entries = [group2entry(g) for g in contents.split("\n\n")]
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/crimson/vep.py", line 99, in <listcomp>
    entries = [group2entry(g) for g in contents.split("\n\n")]
  File "/anaconda3/envs/hamlet-devel/lib/python3.6/site-packages/crimson/vep.py", line 70, in group2entry
    raw_key, raw_value = group.split("\n", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by bow** [comment]
Closing as #14 has been merged.
